# Generated by Django 4.0.2 on 2022-02-17 08:51

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(),
        ),
    ]
